/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pims.ui;

//import pims.other.UserProfile;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.io.*;
import static jdk.nashorn.internal.objects.NativeString.substring;

/**
 * Login is a GUI that allows the end user to use a previously created UserProfile
 *  and log into the application a second time.
 * @author TEAM12
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();
        mainMenu = MainMenu.getInstance();
        
        // If the data file containing existing user profiles does not exist, create it.
        File fout = new File("Data" + File.separator + "user.txt");
        if(!fout.exists()) {
            try {
                fout.createNewFile();
            } catch (IOException ex) {
                System.err.println("Unable to create file");
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameField = new javax.swing.JTextField();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        createUserButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        createUserButton.setText("Help");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PIMS");

        createUserButton1.setText("Options");
        createUserButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel)
                            .addComponent(userNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createUserButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(createUserButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        // TODO add your handling code here:
        this.user = userNameField.getText();
        this.pwd = passwordField.getText();
        MainMenu menu = MainMenu.getInstance();
        if (pwd.contains("admin16") && user.contains("admin")) {
            userNameField.setText("");
            passwordField.setText("");
            close();
            menu.setVisible(true);
        } else {
            try {
                FileInputStream read = new FileInputStream("Data" + File.separator + "user.txt");
                BufferedReader reader = new BufferedReader(new InputStreamReader(read));
                String line = reader.readLine();
                boolean log = false;
                while (line != null && log == false) {
                    if (line.contains("USER:" + user + "&&&&")) {
                        if (line.contains("PASS:" + pwd + "&&&&")) {
                            log = true;
                            this.name = line.substring(line.indexOf("&&&&NAME:") + 
                                    9, line.indexOf("&&&&T"));
                            this.isTeacher = Boolean.valueOf(line.substring(line.indexOf("T:")
                                    + 2));
                            this.setVisible(false);
                            menu.setVisible(true);

                            if (isTeacher) {
                                JOptionPane.showMessageDialog(null, "Welcome! Teacher   " 
                                        + name + "!");
                                assignmentSelector.setAdminStatus(isTeacher);
                            } else {
                                JOptionPane.showMessageDialog(null, "Welcome! Student   " 
                                        + name + "!");
                            }
                        }
                    }
                    line = reader.readLine();
                }
                if (log == false) {
                    JOptionPane.showMessageDialog(null, "Incorrect username or password!",
                            "Please try again!", JOptionPane.ERROR_MESSAGE);
                    passwordField.setText("");
                    this.setVisible(true);
                    mainMenu.setVisible(false);
                }
                read.close();
            } catch (IOException e) {
                System.err.println("Unable to read from file");
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void createUserButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserButton1ActionPerformed
    }

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        // Open CreateUser UI
        CreateUser newUserScreen = new CreateUser();
        this.setVisible(false);
        newUserScreen.setVisible(true);
    }
    
    private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

    /**
     * Creates a UserProfile instance with the current name, password, username, 
     *  and teacher status and returns the new UserProfile instance.
     * @return A UserProfile instance with the data the user entered.
     */
    public UserProfile getCurrentUser() {
        UserProfile newUser = new UserProfile(user, pwd, name, isTeacher);
        return newUser;
    }

    /**
     * Main class that starts off the running of Typing as a Programmer.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* 
         *Set the Nimbus look and feel 
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton createUserButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
    private String name;
    private boolean isTeacher;
    private String pwd;
    private String user;
    private AssignmentSelector assignmentSelector = AssignmentSelector.getInstance();
    private MainMenu mainMenu = null;
    
}
